/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package falconchatserver;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Timer;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author strea
 */
public class ServerManage extends javax.swing.JFrame {
    static ServerSocket ss; 
    static ServerSocket ss1;
    static Socket s;
    static Socket s1; 
    static DataInputStream din; 
    static DataInputStream din1; 
    static DataOutputStream dout;
    static DataOutputStream dout1; 
    static String Message; 
    static String msgin1 = "";
    static String msgin2 = "";
    /**
     * Creates new form ServerManage
     */
    public ServerManage() {
        initComponents();
        btnManage.setOpaque(false);
        btnManage.setContentAreaFilled(false);
        btnManage.setBorderPainted(false);
        btnStatus.setOpaque(false);
        btnStatus.setContentAreaFilled(false);
        btnStatus.setBorderPainted(false);
        btnAuto.setOpaque(false);
        btnAuto.setContentAreaFilled(false);
        btnAuto.setBorderPainted(false);
        btnonoff.setOpaque(false);
        btnonoff.setContentAreaFilled(false);
        btnonoff.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelip = new javax.swing.JLabel();
        labelport = new javax.swing.JLabel();
        labelonline = new javax.swing.JLabel();
        labeloffline = new javax.swing.JLabel();
        labellog = new javax.swing.JLabel();
        btnAuto = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnonoff = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelip.setText("127.0.0.1");
        getContentPane().add(labelip, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 103, 130, 20));

        labelport.setText("127, 128, 129");
        getContentPane().add(labelport, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 159, 130, -1));

        labelonline.setText("N/A");
        getContentPane().add(labelonline, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 103, 186, 197));

        labeloffline.setText("N/A");
        getContentPane().add(labeloffline, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 337, 184, 196));
        getContentPane().add(labellog, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 338, 170, 196));
        getContentPane().add(btnAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 230, 174, 30));

        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, 174, 30));
        getContentPane().add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 190, 174, 30));

        btnonoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnonoffActionPerformed(evt);
            }
        });
        getContentPane().add(btnonoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 545, 378, 26));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/servermanage.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnonoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnonoffActionPerformed
        // TODO add your handling code here:
        ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
        executor.scheduleAtFixedRate((Runnable) new sendmessage(), 0, 1, TimeUnit.SECONDS);
    }//GEN-LAST:event_btnonoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerManage().setVisible(true);
            }
        });
        try //from username 1
        {
            ss = new ServerSocket(fcc.port);
            s = ss.accept();
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());
            while(!msgin1.equals("!exit") || !msgin2.equals("!exit"))
            {
                msgin1 = din.readUTF();
                msgin1 = fcc.username1 + ": " + msgin1; 
            }
            fcc.Message = fcc.Message + "\n" + msgin1;
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "InfoBox: ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        try //from username 2
        {
            ss1 = new ServerSocket(fcc.port1);
            s1 = ss1.accept();
            din1 = new DataInputStream(s1.getInputStream());
            dout1 = new DataOutputStream(s1.getOutputStream()); 
            while(!msgin1.equals("!exit") || !msgin2.equals("!exit"))
            {
                msgin2 = din1.readUTF();
                msgin2 = fcc.username2 + ": " + msgin2; 
            }
            fcc.Message = fcc.Message + "\n" + msgin1; 
        }
        catch (Exception e1)
        {
            JOptionPane.showMessageDialog(null, e1, "InfoBox: ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnonoff;
    private javax.swing.JLabel labelip;
    private javax.swing.JLabel labellog;
    private javax.swing.JLabel labeloffline;
    private javax.swing.JLabel labelonline;
    private javax.swing.JLabel labelport;
    // End of variables declaration//GEN-END:variables
}
